export const WISHLIST_ACTION_TYPES = {
  SET_WISHLIST_ITEMS: "wishlist/SET_WISHLIST_ITEMS",
  SET_WISHLIST_COUNT: "wishlist/SET_WISHLIST_COUNT",
  SET_IS_WISHLIST_OPEN: "wishlist/SET_IS_WISHLIST_OPEN",
};
